server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # proxy opcional para evitar CORS si front llama a /api
    # location /api/ {
    #     proxy_pass http://auth:8080/;
    # }
}
